workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean iOS dependencies
        script: |
          rm -rf ios/Podfile.lock
          rm -rf ios/Pods
          rm -rf ios/.symlinks
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter packages pub get
      - name: Generate iOS configuration
        script: |
          flutter precache --ios
          flutter build ios --config-only
      - name: Install pods with repo update
        script: |
          cd ios && pod install --repo-update
      - name: Flutter analyze
        script: |
          flutter analyze --no-fatal-warnings
        ignore_failure: true
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Flutter build ipa
        script: |
          flutter build ipa --debug --no-codesign
          # Create proper IPA from app bundle
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ../../../Runner.ipa Payload/
          rm -rf Payload
    artifacts:
      - build/ios/ipa/*.ipa
      - Runner.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - f05075985@gmail.com
        notify:
          success: true
          failure: false

  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze --no-fatal-warnings
        ignore_failure: true
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Build APK with Flutter
        script: |
          flutter build apk --debug
    artifacts:
      - build/**/outputs/**/*.apk
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - f05075985@gmail.com
        notify:
          success: true
          failure: false
