name: fitness_flutter
description: BigSteppers - Your fitness companion app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  #BloC  
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  firebase_storage: ^12.4.10
  cloud_firestore: ^5.6.12


  # IOS Icons
  cupertino_icons: ^1.0.8

  # Page View dots indicator
  dots_indicator: ^4.0.1

  # Percent circle
  percent_indicator: ^4.2.3

  # URL launcher
  url_launcher: ^6.2.6

  # Workout Details sliding up panel
  sliding_up_panel: ^2.0.0+1

  # Video player
  video_player: ^2.8.6
  chewie: ^1.7.5


  # Countdown timer
  custom_timer: ^0.2.3

  # Image library
  image_picker: ^1.1.1

  # Reminder notification
  flutter_local_notifications: ^17.1.2

  # Native timezone
  timezone: ^0.9.4

  # Permission handler
  permission_handler: ^11.3.1

  # Package info
  package_info_plus: ^4.2.0

  # Step counter and fitness tracking
  pedometer: ^4.0.1
  
  # Local storage for fitness data
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  
  # Charts for fitness insights
  fl_chart: ^0.66.2

  # Health platform integration (commented out due to compatibility issues)
  # health: ^10.0.0

  # HTTP requests for APIs
  http: ^1.1.0

  # Location and GPS tracking
  geolocator: ^10.1.0
  location: ^5.0.3

  # Google Maps
  google_maps_flutter: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter




# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/onboarding/
    - assets/images/auth/
    - assets/images/home/
    - assets/images/exercises/
    - assets/icons/home/
    - assets/icons/workouts/
    - assets/icons/social_networks/
    - assets/videos/workouts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Bold.otf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #