// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeXzI-6TF6asCRQJIWFwrBpgAsL6wQaVc',
    appId: '1:676499898740:web:d5b1c3ff55c4f375ffec21',
    messagingSenderId: '676499898740',
    projectId: 'bigsteppers-2e714',
    authDomain: 'bigsteppers-2e714.firebaseapp.com',
    storageBucket: 'bigsteppers-2e714.firebasestorage.app',
    measurementId: 'G-S9F6WH6PGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0xrXh8MiadFhXMmeUceizpz1kVLfnhw0',
    appId: '1:676499898740:android:6601c02663b8a6bbffec21',
    messagingSenderId: '676499898740',
    projectId: 'bigsteppers-2e714',
    storageBucket: 'bigsteppers-2e714.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBDiywsXwoLPx6Crh9AfX73P5rmMUoIso',
    appId: '1:676499898740:ios:6304d99795e21b92ffec21',
    messagingSenderId: '676499898740',
    projectId: 'bigsteppers-2e714',
    storageBucket: 'bigsteppers-2e714.firebasestorage.app',
    iosBundleId: 'com.example.fitnessFlutter',
  );

}